import React,{useEffect,useMemo,useState} from "react";
import {Users,Search,Plus,LayoutGrid,List} from "lucide-react";
import {useEmployees} from "../hooks/useEmployees";
import {AddEditEmployeeFormModal} from "../components/employees/AddEditEmployeeFormModal";
import "./Workspace.css";
const initials=n=>(n||"?").split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase();
export default function People(){
 const{employees=[],loading,error,fetchEmployees}=useEmployees();const[search,setSearch]=useState("");const[status,setStatus]=useState("all");const[view,setView]=useState("grid");const[modal,setModal]=useState(false);const[editing,setEditing]=useState(null);
 useEffect(()=>{fetchEmployees()},[]);
 const rows=useMemo(()=>employees.filter(e=>{const q=search.toLowerCase().trim(),name=e.user?.name?.toLowerCase()||"",email=e.user?.email?.toLowerCase()||"";return(!q||name.includes(q)||email.includes(q)||(e.employee_code||"").toLowerCase().includes(q))&&(status==="all"||e.employee_status===status)}),[employees,search,status]);
 if(loading)return <div className="sp-page"><div className="sp-state"><span className="sp-spinner"/>Loading people...</div></div>;
 if(error)return <div className="sp-page"><div className="sp-error">{error}</div></div>;
 return <div className="sp-page"><div className="sp-page-head"><div><span className="sp-eyebrow">WORKFORCE</span><h1>People</h1><p>Manage employees across all organizations.</p></div><button className="sp-primary" onClick={()=>{setEditing(null);setModal(true)}}><Plus size={16}/> Add Member</button></div>
 <div className="sp-toolbar"><div className="sp-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search staff, roles, email..."/></div><select className="sp-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="on_leave">On leave</option></select><div className="sp-icon-toggle"><button className={view==="grid"?"active":""} onClick={()=>setView("grid")}><LayoutGrid size={16}/></button><button className={view==="list"?"active":""} onClick={()=>setView("list")}><List size={16}/></button></div></div>
 {view==="grid"?<div className="sp-card-grid">{rows.map(e=><article className="sp-org-card" key={e.employee_id||e.id}><div className="sp-org-card-head"><span className="sp-avatar sp-avatar--blue">{initials(e.user?.name)}</span><div><h3>{e.user?.name||"Unnamed"}</h3><p>{e.user?.email||"No email"}</p></div></div><div className="sp-org-meta"><div><span>ROLE</span><strong>{e.employee_role||"staff"}</strong></div><div><span>CODE</span><strong>{e.employee_code||"—"}</strong></div><div><span>SHIFTS</span><strong>{e.shifts?.length||0}</strong></div></div><div className="sp-org-actions"><button onClick={()=>{setEditing(e);setModal(true)}}>Edit</button><span className={"sp-status "+(e.employee_status==="inactive"?"inactive":e.employee_status==="on_leave"?"leave":"")}>{e.employee_status||"active"}</span></div></article>)}</div>:<div className="sp-table"><div className="sp-table-head"><span>EMPLOYEE</span><span>ROLE</span><span>ORGANIZATION</span><span>STATUS</span><span>SHIFTS</span></div>{rows.map(e=><div className="sp-table-row" key={e.employee_id||e.id}><div className="sp-person"><span className="sp-avatar sp-avatar--blue">{initials(e.user?.name)}</span><div><strong>{e.user?.name||"Unnamed"}</strong><small>{e.user?.email||"No email"}</small></div></div><span className="sp-chip">{e.employee_role||"staff"}</span><span className="sp-chip">{e.organization?.name||"—"}</span><span className={"sp-status "+(e.employee_status==="inactive"?"inactive":e.employee_status==="on_leave"?"leave":"")}>{e.employee_status||"active"}</span><span className="sp-number">{e.shifts?.length||0}</span></div>)}</div>}
 <AddEditEmployeeFormModal isOpen={modal} onClose={()=>setModal(false)} employee={editing} onSuccess={()=>{setModal(false);fetchEmployees()}}/>
 </div>;
}