import React from "react";
import {LayoutDashboard,CalendarDays,Clock3,Users,Building2,Settings,Sparkles,ArrowUpRight,ChevronsUpDown,X} from "lucide-react";
import {useNavigate,useLocation} from "react-router-dom";
import "./Sidebar.css";
const NAV_ITEMS=[
 {label:"Dashboard",icon:LayoutDashboard,path:"/admin"},
 {label:"Shifts",icon:CalendarDays,path:"/admin/shifts"},
 {label:"Timesheets",icon:Clock3,path:"/admin/timesheets"},
 {label:"People",icon:Users,path:"/admin/people"},
 {label:"Organizations",icon:Building2,path:"/admin/organizations"}
];
export default function Sidebar({isOpen,onClose}){const navigate=useNavigate(),location=useLocation();const active=location.pathname==="/admin"?"Dashboard":NAV_ITEMS.find(x=>location.pathname.startsWith(x.path))?.label||"Dashboard";return <>{isOpen&&<div className="pl-mobile-backdrop" onClick={onClose}/>}<aside className={"pl-sidebar "+(isOpen?"is-open":"")}><div className="pl-brand-row"><div className="pl-brand"><div className="pl-brand-mark">S<span/></div><strong>shiftpulse</strong></div><button className="pl-mobile-close" onClick={onClose}><X size={20}/></button></div><button className="pl-org-switcher" type="button"><div className="pl-org-monogram"><Building2 size={16}/></div><div className="pl-org-copy"><strong>ShiftPulse</strong><span>Admin workspace</span></div><ChevronsUpDown size={14}/></button><nav className="pl-main-nav"><div className="pl-nav-label">WORKSPACE</div><div className="pl-nav-menu">{NAV_ITEMS.map(({label,icon:Icon,path})=><button key={label} className={"pl-nav-item "+(active===label?"is-active":"")} onClick={()=>{navigate(path);onClose()}}><Icon size={19} strokeWidth={1.8}/><span>{label}</span>{active===label&&<span className="pl-active-dot"/>}</button>)}</div></nav><div className="pl-sidebar-spacer"/><div className="pl-support-card"><div className="pl-support-title"><Sparkles size={16}/><strong>Stay on track</strong></div><p>Manage your people, schedules and organizations from one workspace.</p><button type="button" className="pl-help-link">Help center <ArrowUpRight size={14}/></button></div><button className="pl-settings-link" type="button"><Settings size={19}/><span>Settings</span></button><div className="pl-copyright">© 2026 ShiftPulse</div></aside></>}